In [1]:
from MIOFlow.models import make_model
import torch

In [2]:
batch_size = 4
feature_dim = 5
output_dim = 5

x = torch.randn(batch_size, feature_dim)
# m0 = torch.ones(batch_size, 1)
# xm = torch.cat([x, m0], dim=1)
t = torch.linspace(0, 1, 7)

model = make_model(feature_dims=feature_dim, which='ode_growth_rate')

In [3]:
xt, mt = model(x, t)

In [4]:
xt.shape, mt.shape

(torch.Size([4, 5]), torch.Size([4]))

In [5]:
xtseq, mtseq = model(x, t, return_whole_sequence=True)

In [6]:
xtseq.shape

torch.Size([7, 4, 5])

In [7]:
mtseq.shape

torch.Size([7, 4])

In [8]:
torch.nn.functional.softmax(mt, dim=-1) * mt.shape[-1]

tensor([0.7505, 1.1888, 1.1637, 0.8970], grad_fn=<MulBackward0>)

In [9]:
torch.exp(mt)/torch.exp(mt).sum(dim=0)

tensor([0.1876, 0.2972, 0.2909, 0.2242], grad_fn=<DivBackward0>)

In [10]:
torch.nn.functional.softmax(mtseq, dim=-1) * mtseq.shape[-1]

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [0.9609, 1.0290, 1.0241, 0.9860],
        [0.9211, 1.0584, 1.0493, 0.9711],
        [0.8804, 1.0887, 1.0756, 0.9553],
        [0.8383, 1.1206, 1.1033, 0.9378],
        [0.7950, 1.1541, 1.1325, 0.9184],
        [0.7505, 1.1888, 1.1637, 0.8970]], grad_fn=<MulBackward0>)

In [11]:
xtseq.shape

torch.Size([7, 4, 5])

In [12]:
mtseq.unsqueeze(2).shape

torch.Size([7, 4, 1])

In [13]:
xmseq = torch.cat([xtseq, mtseq.unsqueeze(2)], dim=-1)
xmseq.shape

torch.Size([7, 4, 6])

In [14]:
dxdts = torch.stack([model.func(t[i], xmseq[i]) for i in range(len(t))])

In [15]:
dxdts.shape

torch.Size([7, 4, 6])

In [16]:
mt.unsqueeze(1).shape

torch.Size([4, 1])

In [17]:
model.func

ToyODE(
  (seq): Sequential(
    (0): Linear(in_features=9, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=6, bias=True)
  )
)

In [18]:
xt.shape

torch.Size([4, 5])

In [19]:
mt.shape

torch.Size([4])

In [20]:
xm = torch.cat([xt, mt.unsqueeze(-1)], dim=-1)
dxdt = model.func(t[-1], xm)

In [21]:
dxdt[...,:-1].shape

torch.Size([4, 5])

In [22]:
mtseq.shape

torch.Size([7, 4])

In [23]:
xtseq.shape

torch.Size([7, 4, 5])

In [24]:
t.shape

torch.Size([7])

In [25]:
t[[0,1,2],...]

tensor([0.0000, 0.1667, 0.3333])

In [26]:
mt.shape

torch.Size([4])

In [27]:
(dxdt * mt.unsqueeze(-1)).shape

torch.Size([4, 6])

In [28]:
dxdts.shape

torch.Size([7, 4, 6])

In [29]:
mtseq.shape

torch.Size([7, 4])

In [30]:
(dxdts * mtseq.unsqueeze(-1)).shape

torch.Size([7, 4, 6])

In [31]:
torch.nn.functional.softmax(mtseq, dim=-1).shape

torch.Size([7, 4])

In [32]:
mtseq.shape[-1]

4

In [33]:
torch.nn.functional.softmax(mt, dim=-1).shape

torch.Size([4])

In [34]:
mt.shape[-1]

4

In [35]:
def func_end_0(t, x):
    xm = model.func(t, x)
# mt[[0,2,4,6,8]] = 0.
model.func(t[-1], xm).shape

torch.Size([4, 6])

In [36]:
xm[...,-1].shape

torch.Size([4])

In [37]:
xm.shape

torch.Size([4, 6])

In [38]:
xmseq.shape

torch.Size([7, 4, 6])

In [39]:
xm[[0,2],-1] = 0.

In [40]:
xm

tensor([[ 1.5279,  0.4715, -0.9094, -0.2058,  2.3502,  0.0000],
        [-0.9513, -0.0902,  0.4583,  2.2913,  1.4278,  1.4056],
        [ 0.8226,  2.1026,  1.3879,  0.6041,  2.0260,  0.0000],
        [ 0.5811, -0.9234, -1.4337, -1.7217, -1.2556,  1.1239]],
       grad_fn=<CopySlices>)

In [41]:
dxmdt = model.func(t[-1], xm)

In [42]:
dxmdt

tensor([[ 0.6087,  0.2030,  0.1904, -0.1467,  0.4246, -0.0695],
        [ 0.1980,  0.0136,  0.2122, -0.0470,  0.1949,  0.3457],
        [ 0.4026,  0.4142,  0.1505, -0.0345,  0.6536,  0.3309],
        [ 0.1531, -0.0547, -0.0480, -0.0100, -0.2726,  0.1750]],
       grad_fn=<AddmmBackward0>)

In [43]:
xm.shape

torch.Size([4, 6])

In [44]:
xt.shape

torch.Size([4, 5])

In [45]:
xtseq.shape

torch.Size([7, 4, 5])

In [46]:
xm.shape

torch.Size([4, 6])

In [47]:
xmseq.shape

torch.Size([7, 4, 6])

In [49]:
xmseq.shape

torch.Size([7, 4, 6])

In [50]:
xm.shape

torch.Size([4, 6])

In [54]:
xtseq.shape

torch.Size([7, 4, 5])

In [55]:
xtseq.norm(dim=-1).shape

torch.Size([7, 4])

In [64]:
(xtseq / xtseq.norm(dim=-1, keepdim=True)).shape

torch.Size([7, 4, 5])

In [65]:
torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0).shape

torch.Size([6, 4, 5])

In [66]:
torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0)

tensor([[[ 1.9382e-02,  5.0963e-03,  2.2639e-02, -1.7424e-02,  1.1753e-03],
         [ 1.2942e-02, -4.2188e-03,  1.0558e-02,  7.7379e-04,  8.6896e-03],
         [ 8.9051e-03, -2.8163e-03, -6.2940e-03, -1.0093e-02,  9.4221e-03],
         [ 7.8263e-03,  1.2061e-02,  2.4964e-03,  2.7027e-03, -1.7407e-02]],

        [[ 1.9138e-02,  5.0414e-03,  2.3193e-02, -1.4788e-02,  1.7363e-04],
         [ 1.4647e-02, -3.6606e-03,  1.0864e-02,  5.4300e-04,  9.7533e-03],
         [ 8.8417e-03, -3.0878e-03, -6.6915e-03, -9.5624e-03,  9.2970e-03],
         [ 9.0909e-03,  1.0276e-02,  2.5969e-03,  4.1075e-03, -1.6378e-02]],

        [[ 1.8720e-02,  4.9315e-03,  2.3322e-02, -1.2236e-02, -8.0264e-04],
         [ 1.6208e-02, -3.1886e-03,  1.1015e-02,  2.5803e-04,  1.0587e-02],
         [ 8.6409e-03, -3.1736e-03, -6.9879e-03, -9.1124e-03,  8.9894e-03],
         [ 1.0227e-02,  8.8009e-03,  2.6943e-03,  5.2797e-03, -1.5431e-02]],

        [[ 1.8165e-02,  4.8559e-03,  2.2949e-02, -9.9117e-03, -1.8041e-03],
      

In [68]:
torch.square(torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0)).mean()

tensor(0.0001, grad_fn=<MeanBackward0>)

In [69]:
torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0)

tensor([[[ 1.9382e-02,  5.0963e-03,  2.2639e-02, -1.7424e-02,  1.1753e-03],
         [ 1.2942e-02, -4.2188e-03,  1.0558e-02,  7.7379e-04,  8.6896e-03],
         [ 8.9051e-03, -2.8163e-03, -6.2940e-03, -1.0093e-02,  9.4221e-03],
         [ 7.8263e-03,  1.2061e-02,  2.4964e-03,  2.7027e-03, -1.7407e-02]],

        [[ 1.9138e-02,  5.0414e-03,  2.3193e-02, -1.4788e-02,  1.7363e-04],
         [ 1.4647e-02, -3.6606e-03,  1.0864e-02,  5.4300e-04,  9.7533e-03],
         [ 8.8417e-03, -3.0878e-03, -6.6915e-03, -9.5624e-03,  9.2970e-03],
         [ 9.0909e-03,  1.0276e-02,  2.5969e-03,  4.1075e-03, -1.6378e-02]],

        [[ 1.8720e-02,  4.9315e-03,  2.3322e-02, -1.2236e-02, -8.0264e-04],
         [ 1.6208e-02, -3.1886e-03,  1.1015e-02,  2.5803e-04,  1.0587e-02],
         [ 8.6409e-03, -3.1736e-03, -6.9879e-03, -9.1124e-03,  8.9894e-03],
         [ 1.0227e-02,  8.8009e-03,  2.6943e-03,  5.2797e-03, -1.5431e-02]],

        [[ 1.8165e-02,  4.8559e-03,  2.2949e-02, -9.9117e-03, -1.8041e-03],
      