In [29]:
from MIOFlow.models import make_model
import torch

In [30]:
batch_size = 4
feature_dim = 2
output_dim = 2

x = torch.randn(batch_size, feature_dim)
# m0 = torch.ones(batch_size, 1)
# xm = torch.cat([x, m0], dim=1)
t = torch.linspace(0, 1, 7)

model = make_model(feature_dims=feature_dim, which='ode_growth_rate', separate_network_m=True)
# model = make_model(feature_dims=feature_dim, which='ode_growth_rate', separate_network_m=False)

In [31]:
model.func.seq

<bound method ToyODE.__init__.<locals>.seq of ToyODE(
  (x_seq): Sequential(
    (0): Linear(in_features=5, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=2, bias=True)
  )
  (m_seq): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
)>

In [32]:
model.func.seq


<bound method ToyODE.__init__.<locals>.seq of ToyODE(
  (x_seq): Sequential(
    (0): Linear(in_features=5, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=2, bias=True)
  )
  (m_seq): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
)>

In [33]:
model.func(t[0], torch.cat([x, torch.zeros_like(x[...,-1:])], dim=-1))

tensor([[ 0.0108,  0.1521, -0.0753],
        [-0.1025, -0.0411, -0.0840],
        [ 0.0162,  0.2084, -0.0844],
        [ 0.0238,  0.1275, -0.1422]], grad_fn=<CatBackward0>)

In [34]:
model.func.m_seq

Sequential(
  (0): Linear(in_features=6, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=1, bias=True)
)

In [35]:
model.func.seq

<bound method ToyODE.__init__.<locals>.seq of ToyODE(
  (x_seq): Sequential(
    (0): Linear(in_features=5, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=2, bias=True)
  )
  (m_seq): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
)>

In [36]:
xm = torch.cat([x, torch.zeros_like(x[...,-1:])], dim=-1)
model.func(t[0], xm)

tensor([[ 0.0108,  0.1521, -0.0753],
        [-0.1025, -0.0411, -0.0840],
        [ 0.0162,  0.2084, -0.0844],
        [ 0.0238,  0.1275, -0.1422]], grad_fn=<CatBackward0>)

In [37]:
x.shape

torch.Size([4, 2])

In [38]:
xm.shape

torch.Size([4, 3])

In [39]:
model.func(t[0], xm).shape

torch.Size([4, 3])

In [40]:
xtseq, mtseq = model(x, t[[0,-1]], return_whole_sequence=False)

In [41]:
xtseq.shape

torch.Size([4, 2])

In [42]:
mtseq.shape

torch.Size([4])

In [43]:
torch.nn.functional.softmax(mt, dim=-1) * mt.shape[-1]

NameError: name 'mt' is not defined

In [ ]:
torch.exp(mt)/torch.exp(mt).sum(dim=0)

tensor([0.2326, 0.2390, 0.2821, 0.2463], grad_fn=<DivBackward0>)

In [ ]:
torch.nn.functional.softmax(mtseq, dim=-1) * mtseq.shape[-1]

tensor([[1.0000, 1.0000, 1.0000, 1.0000],
        [0.9836, 0.9942, 1.0223, 0.9999],
        [0.9699, 0.9876, 1.0432, 0.9992],
        [0.9582, 0.9803, 1.0640, 0.9975],
        [0.9478, 0.9722, 1.0853, 0.9946],
        [0.9387, 0.9638, 1.1069, 0.9907],
        [0.9306, 0.9558, 1.1282, 0.9853]], grad_fn=<MulBackward0>)

In [ ]:
xtseq.shape

torch.Size([7, 4, 5])

In [ ]:
mtseq.unsqueeze(2).shape

torch.Size([7, 4, 1])

In [ ]:
xmseq = torch.cat([xtseq, mtseq.unsqueeze(2)], dim=-1)
xmseq.shape

torch.Size([7, 4, 6])

In [ ]:
dxdts = torch.stack([model.func(t[i], xmseq[i]) for i in range(len(t))])

In [ ]:
dxdts.shape

torch.Size([7, 4, 6])

In [ ]:
mt.unsqueeze(1).shape

torch.Size([4, 1])

In [ ]:
model.func

ToyODE(
  (x_seq): Sequential(
    (0): Linear(in_features=8, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=5, bias=True)
  )
  (m_seq): Sequential(
    (0): Linear(in_features=9, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
)

In [ ]:
xt.shape

torch.Size([4, 5])

In [ ]:
mt.shape

torch.Size([4])

In [ ]:
xm = torch.cat([xt, mt.unsqueeze(-1)], dim=-1)
dxdt = model.func(t[-1], xm)

In [ ]:
dxdt[...,:-1].shape

torch.Size([4, 5])

In [ ]:
mtseq.shape

torch.Size([7, 4])

In [ ]:
xtseq.shape

torch.Size([7, 4, 5])

In [ ]:
t.shape

torch.Size([7])

In [ ]:
t[[0,1,2],...]

tensor([0.0000, 0.1667, 0.3333])

In [ ]:
mt.shape

torch.Size([4])

In [ ]:
(dxdt * mt.unsqueeze(-1)).shape

torch.Size([4, 6])

In [ ]:
dxdts.shape

torch.Size([7, 4, 6])

In [ ]:
mtseq.shape

torch.Size([7, 4])

In [ ]:
(dxdts * mtseq.unsqueeze(-1)).shape

torch.Size([7, 4, 6])

In [ ]:
torch.nn.functional.softmax(mtseq, dim=-1).shape

torch.Size([7, 4])

In [ ]:
mtseq.shape[-1]

4

In [ ]:
torch.nn.functional.softmax(mt, dim=-1).shape

torch.Size([4])

In [ ]:
mt.shape[-1]

4

In [ ]:
def func_end_0(t, x):
    xm = model.func(t, x)
# mt[[0,2,4,6,8]] = 0.
model.func(t[-1], xm).shape

torch.Size([4, 6])

In [ ]:
xm[...,-1].shape

torch.Size([4])

In [ ]:
xm.shape

torch.Size([4, 6])

In [ ]:
xmseq.shape

torch.Size([7, 4, 6])

In [ ]:
xm[[0,2],-1] = 0.

In [ ]:
xm

tensor([[ 1.8315,  0.1374,  1.7242, -1.9497,  2.6068,  0.0000],
        [ 0.8588,  0.0762, -0.1377,  0.2121, -0.5307,  0.8042],
        [ 0.2150,  0.5789, -1.3497,  1.5216,  0.8248,  0.0000],
        [-0.2267, -0.0918,  0.8110, -1.9355, -0.1192,  0.8346]],
       grad_fn=<CopySlices>)

In [ ]:
dxmdt = model.func(t[-1], xm)

In [ ]:
dxmdt

tensor([[ 0.2918, -0.3380, -0.3800,  0.0608,  0.6475, -0.1845],
        [ 0.0560, -0.2139, -0.1045, -0.1400,  0.3072, -0.1385],
        [ 0.1257, -0.2282, -0.1437, -0.2760,  0.0311,  0.0013],
        [-0.0310, -0.2848, -0.0180,  0.0298,  0.5136, -0.1734]],
       grad_fn=<CatBackward0>)

In [ ]:
xm.shape

torch.Size([4, 6])

In [ ]:
xt.shape

torch.Size([4, 5])

In [ ]:
xtseq.shape

torch.Size([7, 4, 5])

In [ ]:
xm.shape

torch.Size([4, 6])

In [ ]:
xmseq.shape

torch.Size([7, 4, 6])

In [ ]:
xmseq.shape

torch.Size([7, 4, 6])

In [ ]:
xm.shape

torch.Size([4, 6])

In [ ]:
xtseq.shape

torch.Size([7, 4, 5])

In [ ]:
xtseq.norm(dim=-1).shape

torch.Size([7, 4])

In [ ]:
(xtseq / xtseq.norm(dim=-1, keepdim=True)).shape

torch.Size([7, 4, 5])

In [ ]:
torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0).shape

torch.Size([6, 4, 5])

In [ ]:
torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0)

tensor([[[ 0.0094, -0.0153, -0.0119,  0.0105,  0.0177],
         [ 0.0287, -0.0231, -0.0009, -0.0035,  0.0185],
         [ 0.0107, -0.0098, -0.0166, -0.0093,  0.0032],
         [-0.0028, -0.0172,  0.0179,  0.0010,  0.0196]],

        [[ 0.0088, -0.0150, -0.0135,  0.0105,  0.0179],
         [ 0.0299, -0.0237, -0.0025, -0.0054,  0.0218],
         [ 0.0107, -0.0100, -0.0164, -0.0098,  0.0033],
         [-0.0019, -0.0170,  0.0165,  0.0009,  0.0227]],

        [[ 0.0082, -0.0147, -0.0151,  0.0103,  0.0178],
         [ 0.0313, -0.0254, -0.0041, -0.0082,  0.0254],
         [ 0.0109, -0.0106, -0.0162, -0.0103,  0.0033],
         [-0.0012, -0.0164,  0.0148,  0.0008,  0.0260]],

        [[ 0.0076, -0.0143, -0.0165,  0.0100,  0.0175],
         [ 0.0329, -0.0284, -0.0057, -0.0116,  0.0296],
         [ 0.0110, -0.0112, -0.0161, -0.0109,  0.0034],
         [-0.0002, -0.0159,  0.0129,  0.0007,  0.0293]],

        [[ 0.0069, -0.0141, -0.0179,  0.0095,  0.0170],
         [ 0.0341, -0.0319, -0.0068, -0.

In [ ]:
torch.square(torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0)).mean()

tensor(0.0003, grad_fn=<MeanBackward0>)

In [ ]:
torch.diff(xtseq / xtseq.norm(dim=-1, keepdim=True), dim=0)

tensor([[[ 0.0094, -0.0153, -0.0119,  0.0105,  0.0177],
         [ 0.0287, -0.0231, -0.0009, -0.0035,  0.0185],
         [ 0.0107, -0.0098, -0.0166, -0.0093,  0.0032],
         [-0.0028, -0.0172,  0.0179,  0.0010,  0.0196]],

        [[ 0.0088, -0.0150, -0.0135,  0.0105,  0.0179],
         [ 0.0299, -0.0237, -0.0025, -0.0054,  0.0218],
         [ 0.0107, -0.0100, -0.0164, -0.0098,  0.0033],
         [-0.0019, -0.0170,  0.0165,  0.0009,  0.0227]],

        [[ 0.0082, -0.0147, -0.0151,  0.0103,  0.0178],
         [ 0.0313, -0.0254, -0.0041, -0.0082,  0.0254],
         [ 0.0109, -0.0106, -0.0162, -0.0103,  0.0033],
         [-0.0012, -0.0164,  0.0148,  0.0008,  0.0260]],

        [[ 0.0076, -0.0143, -0.0165,  0.0100,  0.0175],
         [ 0.0329, -0.0284, -0.0057, -0.0116,  0.0296],
         [ 0.0110, -0.0112, -0.0161, -0.0109,  0.0034],
         [-0.0002, -0.0159,  0.0129,  0.0007,  0.0293]],

        [[ 0.0069, -0.0141, -0.0179,  0.0095,  0.0170],
         [ 0.0341, -0.0319, -0.0068, -0.

In [ ]:
dxdts.norm(dim=-1) - torch.arange(7).unsqueeze(-1)

tensor([[ 0.8355,  0.3327,  0.4329,  0.4719],
        [-0.1410, -0.6593, -0.5749, -0.5095],
        [-1.1208, -1.6442, -1.5795, -1.4876],
        [-2.1018, -2.6306, -2.5839, -2.4633],
        [-3.0850, -3.6115, -3.5858, -3.4367],
        [-4.0656, -4.5891, -4.5742, -4.4106],
        [-5.0439, -5.5607, -5.5595, -5.3859]], grad_fn=<SubBackward0>)